//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSchool.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportSchoolEntities : DbContext
    {
        public SportSchoolEntities()
            : base("name=SportSchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coach> Coach { get; set; }
        public virtual DbSet<Parents> Parents { get; set; }
        public virtual DbSet<RecordingsOffClasses> RecordingsOffClasses { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<Sessions> Sessions { get; set; }
        public virtual DbSet<Sports> Sports { get; set; }
        public virtual DbSet<SportsAndCoach> SportsAndCoach { get; set; }
        public virtual DbSet<SportsStudents> SportsStudents { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
