
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSchool.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Coach
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Coach()
    {

        this.Schedules = new HashSet<Schedules>();

        this.Sessions = new HashSet<Sessions>();

        this.SportsAndCoach = new HashSet<SportsAndCoach>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string SurName { get; set; }

    public string Patronymic { get; set; }

    public string Telephone { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Schedules> Schedules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sessions> Sessions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SportsAndCoach> SportsAndCoach { get; set; }

}

}
