
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSchool.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Parents
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Parents()
    {

        this.Student = new HashSet<Student>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string SurName { get; set; }

    public string Patronymic { get; set; }

    public string Address { get; set; }

    public string Telephone { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Student> Student { get; set; }

}

}
