//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public int Id { get; set; }
        public string DayOfWeek { get; set; }
        public Nullable<System.TimeSpan> TimeSlot { get; set; }
        public Nullable<int> IdCoach { get; set; }
        public Nullable<int> IdSession { get; set; }
    
        public virtual Coach Coach { get; set; }
    }
}
