//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsSchool.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsAndCoach
    {
        public int Id { get; set; }
        public int IdCoach { get; set; }
        public int IdSports { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Sports Sports { get; set; }
    }
}
