
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSchool.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class SportsStudents
{

    public int Id { get; set; }

    public int IdSport { get; set; }

    public int IdStudent { get; set; }



    public virtual Sports Sports { get; set; }

    public virtual Student Student { get; set; }

}

}
