
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSchool.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.RecordingsOffClasses = new HashSet<RecordingsOffClasses>();

        this.SportsStudents = new HashSet<SportsStudents>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string SurName { get; set; }

    public string Patronymic { get; set; }

    public Nullable<System.DateTime> BirthDate { get; set; }

    public Nullable<int> IdParents { get; set; }



    public virtual Parents Parents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RecordingsOffClasses> RecordingsOffClasses { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SportsStudents> SportsStudents { get; set; }

}

}
