
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SportsSchool.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Users
{

    public string Login { get; set; }

    public string Password { get; set; }

    public string Mail { get; set; }

    public Nullable<int> IdRole { get; set; }

    public string Name { get; set; }

    public string SurName { get; set; }

    public string MiddleName { get; set; }



    public virtual Role Role { get; set; }

}

}
